### PR TITLE
Use Jekyll Primer theme

### PR DESCRIPTION
**Pull request by benbalter**
It looks like the site was intended to vendor Primer into the `node_modules` directory, and include it as a dependency via the `index.scss` file, but since that directory is `.gitignored`, it wasn't actually vendored. 

Instead, since no theme is specified, Primer is being used by default. The load paths for Primer modules are valid, even though they are not part of the repository (GitHub Pages does not clone down Node dependencies as part of the build process).

This Pull request makes that dependency explicit, by adding a Gemfile (in parallel to https://github.com/natfriedman/hello/pull/1) with the [GitHub Pages Gem](https://github.com/github/pages-gem), to better replicate the production environment locally, and declares `primer` as the theme, alleviating the need to have Node or NPM installed to build the site (The GitHub Pages Gem contains Primer).

The resulting output should be identical, without the external dependency:

### Before

screen shot 2018-06-04 at 6 14 25 pm

### After

screen shot 2018-06-04 at 6 13 59 pm

### CODE REVIEW

**Comment by IamManchanda** [comment]
@natfriedman I know this is not the right place to contact you 

But what about Atom?
Isn't Atom and VSCode the two main competitors on code editing world ...
So what happens to both of them going forward ... Will atom be moved and joined to VS Code??

**Comment by IamManchanda** [comment]
So many dislikes for just asking a question? Huh!

CMON .... that's not done community! My Question is a very serious one ... What is the future of Atom??

I know this is not the right place to ask this question and I am sorry about it, but
Please reply @natfriedman @benbalter

**Comment by jakoblorz** [comment]
@IamManchanda well I guess you could wait for the ama @natfriedman mentioned in his post. Atom has a huge following which is why I am sure he will find this question in the ama as well.

**Comment by benbalter** [comment]
@IamManchanda Thanks for your concern. Atom remains key to GitHub. Our product roadmap is set, and the team will continue all of their great work.

**Pull request merged**
